# Generated by Django 2.2.10 on 2021-01-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='history',
        ),
    ]
